functionality:
  name: baseline_babel
  namespace: predict_modality_methods
  version: dev
  description: Learn a deep-learning model with BABEL.
  info:
    type: sota
    label: BABEL
    doi: "10.1073/pnas.2023070118"
  authors:
    - name: Alejandro Granados
      email: alejandro.granados@czbiohub.org
      roles: [ author, maintainer ]
      props: { github: agranado }
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ contributor ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The train mod1 profiles."
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The train mod2 profiles."
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The test mod1 profiles."
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "The predicted test mod2 profiles."
      required: true
  resources:
    - type: r_script
      path: script.R
  # babel doesn't work on the resources_test data
  # tests:
  #   - type: r_script
  #     path: ../../unit_tests/test_method.R
  #   - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    run_args: 
      - "--shm-size=1024m"
    setup:
      - type: docker
        run: 
          - wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda && /opt/conda/bin/conda -V
          - cd / && git clone --depth 1 https://github.com/rcannood/babel.git
          - cd /babel && /opt/conda/bin/conda env create -f environment.yml
      - type: r
        bioc: [ DropletUtils ]
      - type: docker
        env: 
          - PATH=/opt/conda/bin/:$PATH
  - type: nextflow
    labels: [ midmem, lowtime, lowcpu ]
