functionality:
  name: dummy_semisolution
  namespace: match_modality_methods
  version: dev
  description: Returns the ground-truth pairing.
  info:
    type: positive_control
    label: Semi-solution
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_test_sol"
      type: "file"
      example: "dataset_solution.h5ad"
      description: "The pairing of test mod1&mod2 profiles."
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "The predicted pairing of test mod1&mod2 profiles."
      required: true
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: test_method.R
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
  - type: nextflow
    publish: true
    labels: [ lowmem, lowtime, lowcpu ]
