functionality:
  name: dummy_solution
  namespace: predict_modality_methods
  version: dev
  description: Returns the ground-truth solution.
  info:
    type: positive_control
    label: Solution
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_test_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset, train cells.
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: test_method.R
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        packages: [ lmds ]
  - type: nextflow
    publish: true
    labels: [ lowmem, lowtime, lowcpu ]
