functionality:
  name: nmi
  namespace: joint_embedding_metrics
  version: dev
  description: Normalised mutual information (NMI)
  authors:
    - name: Michaela Mueller
      email: mumichae@in.tum.de
      roles: [ author, maintainer ]
      props: { github: mumichae, orcid: "0000-0002-1401-1785" }
  arguments:
    - name: --input_prediction
      type: file
      description: Prediction by a method
      required: true
      example: prediction.h5ad
    - name: --input_solution
      type: file
      description: Gold standard solution.
      required: true
      example: solution.h5ad
    - name: --output
      type: file
      direction: output
      description: Metric scores by comparing the prediction to the gold standard solution.
      required: true
      example: output.h5ad
    - name: --debug
      type: boolean
      description: Verbose output for debugging.
      default: False
      required: false
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: ../../unit_tests/test_metric.py
    - path: ../../../../resources_test
    - path: metric_meta_nmi.tsv
      dest: metric_meta.tsv
platforms:
  - type: docker
    image: mumichae/scib-base:1.0.0
  - type: native
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
