---
title: "Match Modality - Pilot Analysis"
output: pdf_document
fontsize: 10pt
geometry: margin=1cm
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=10, fig.height=12, warning = FALSE)
knitr::opts_knit$set(root.dir = '..')

library(tidyverse)
library(patchwork)
library(kableExtra)
task <- "match_modality"
```

```{r tsv, include=FALSE}
meta_ds <- read_tsv("results/meta_datasets.tsv")
colnames(meta_ds) <- ifelse(!grepl("dataset_", colnames(meta_ds)), paste0("dataset_", colnames(meta_ds)), colnames(meta_ds))
meta_ms <- read_tsv("results/meta_methods.tsv") %>% filter(task == !!task)
colnames(meta_ms) <- ifelse(!grepl("method_", colnames(meta_ms)), paste0("method_", colnames(meta_ms)), colnames(meta_ms))

df <- 
  # read in all columns as strings because of infinite values in table
  readr::read_tsv(
    "output/pilot_inhouse/match_modality/output.final_scores.output_scores.tsv",
    col_types = c(dataset_id = "c", method_id = "c", metric_id = "c", dataset_subtask = "c", value = "d", value_after_default = "d")
  ) %>%
  mutate(
    # extract meta info
    dataset_id_orig = gsub("_MM$", "", dataset_id),
    dataset_phase = gsub(".*_", "", dataset_id_orig)
  ) %>% 
  left_join(meta_ds, by = c("dataset_id_orig" = "dataset_id")) %>%
  left_join(meta_ms, by = "method_id") %>%
  select(-value) %>%
  spread(metric_id, value_after_default) %>% 
  mutate(
    format_check = (correct_format + finished) / 2
  )
write_tsv(df %>% gather(metric_id, value, -starts_with("dataset_"), -starts_with("method_"), -starts_with("metric_")), "results/inhouse_match_modality_scores.tsv")
```

```{r summtsv, include=FALSE}
summ <- df %>% 
  gather(metric_id, value, -starts_with("dataset_"), -starts_with("method_")) %>% 
  group_by(method_id, metric_id) %>%
  summarise(
    mean = mean(value),
    var = var(value),
    .groups = "drop"
  ) %>% 
  left_join(meta_ms, by = "method_id")
write_tsv(summ, "results/inhouse_match_modality_summary.tsv")
```

\newpage
## Visualise results
```{r gather, echo=FALSE}
# gather columns from wide to long format
dfg <- df %>%
  mutate(filter = finished > 0) %>%
  select(-correct_format, -finished) %>%
  filter(!grepl("solution", method_id)) %>%
  gather(metric_id, value, -starts_with("dataset_"), -starts_with("method"), -filter) %>%
  filter(filter | metric_id %in% c("finished", "correct_format", "format_check"))
```

Colour by method.

```{r swarm1, echo=FALSE}
patchwork::wrap_plots(
  ggplot(dfg) +
    ggbeeswarm::geom_quasirandom(aes(method_id, value, colour = method_id), groupOnX = TRUE, size = 1) +
    facet_wrap(~metric_id, scales = "free_y", ncol = 4) +
    scale_colour_brewer(palette = "Set1") +
    labs(x = NULL, y = "Metric Value", colour = "Method"),
  ggplot(dfg) +
    geom_boxplot(aes(method_id, value, colour = method_id)) +
    facet_wrap(~metric_id, scales = "free_y", ncol = 4) +
    scale_colour_brewer(palette = "Set1") +
    labs(x = NULL, y = "Metric Value", colour = "Method"),
  ncol = 1
  # guides = "collect"
) &
  theme_bw() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 30, hjust = 1))
```


\newpage
Colour by modality group.

```{r swarm3, echo=FALSE}
patchwork::wrap_plots(
  ggplot(dfg) +
    ggbeeswarm::geom_quasirandom(aes(method_id, value, colour = dataset_subtask), groupOnX = TRUE, size = 1) +
    facet_wrap(~metric_id, scales = "free_y") +
    scale_colour_brewer(palette = "Set2") +
    labs(x = NULL, y = "Metric Value", colour = "Modality\ngroup"),
  ggplot(dfg) +
    geom_boxplot(aes(method_id, value, colour = dataset_subtask)) +
    facet_wrap(~metric_id, scales = "free_y") +
    scale_colour_brewer(palette = "Set2") +
    labs(x = NULL, y = "Metric Value", colour = "Modality\ngroup"),
  ncol = 1
  # guides = "collect"
) &
  theme_bw() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 30, hjust = 1))
```


\newpage
Colour by phase.

```{r swarm2, echo=FALSE}
patchwork::wrap_plots(
  ggplot(dfg) +
    ggbeeswarm::geom_quasirandom(aes(method_id, value, colour = dataset_phase), groupOnX = TRUE, size = 1) +
    facet_wrap(~metric_id, scales = "free_y", ncol = 4) +
    scale_colour_brewer(palette = "Dark2") +
    labs(x = NULL, y = "Metric Value", colour = "Phase"),
  ggplot(dfg) +
    geom_boxplot(aes(method_id, value, colour = dataset_phase)) +
    facet_wrap(~metric_id, scales = "free_y", ncol = 4) +
    scale_colour_brewer(palette = "Dark2") +
    labs(x = NULL, y = "Metric Value", colour = "Phase"),
  ncol = 1
  # guides = "collect"
) &
  theme_bw() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 30, hjust = 1))
```


\newpage
Comparing most interesting metrics.

```{r scatter2, fig.width=10, fig.height=10}
# TODO: check NA values, check negative values in selexted metrics

selected_metrics <- c("match_probability_mod1", "match_probability_mod2", "pairing_aupr", "pairing_auroc")
GGally::ggpairs(
  df,
  mapping = aes(colour = method_type, fill = method_type), 
  columns = selected_metrics,
  diag = list(continuous = "barDiag", discrete = "barDiag", na = "naDiag"),
  upper = list(continuous = "na", combo = "na", discrete = "na", na = "na")
) & theme_bw() & 
  scale_colour_brewer(palette = "Set2") &
  scale_fill_brewer(palette = "Set2")
```
