---
title: "Predict Modality - Pilot Analysis"
output: pdf_document
fontsize: 10pt
geometry: margin=1cm
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=10, fig.height=12)
knitr::opts_knit$set(root.dir = '..')

library(tidyverse)
library(patchwork)
library(kableExtra)
task <- "predict_modality"
```


```{r tsv, include=FALSE}
meta_ds <- read_tsv("results/meta_datasets.tsv")
colnames(meta_ds) <- ifelse(!grepl("dataset_", colnames(meta_ds)), paste0("dataset_", colnames(meta_ds)), colnames(meta_ds))
meta_ms <- read_tsv("results/meta_methods.tsv") %>% filter(task == !!task)
colnames(meta_ms) <- ifelse(!grepl("method_", colnames(meta_ms)), paste0("method_", colnames(meta_ms)), colnames(meta_ms))
meta_metrics <- read_tsv("results/meta_metrics.tsv") %>% filter(task == !!task)
colnames(meta_metrics) <- ifelse(!grepl("metric_", colnames(meta_metrics)), paste0("metric_", colnames(meta_metrics)), colnames(meta_metrics))

df <- 
  # read in all columns as strings because of infinite values in table
  readr::read_tsv(
    "output/pilot/predict_modality/output.extract_scores.output.tsv",
    col_types = c(.default = "c")
  ) %>%
  mutate(
    # manually convert to floats afterwards
    value = as.numeric(value),
    # workaround for numerical division by almost-zero
    value = ifelse(grepl("pearson|spearman", metric_id) & value > 2, 0, value),
    # zap small values
    value = ifelse(grepl("pearson|spearman", metric_id) & value > 1, 1, value),
    dataset_id_orig = gsub("_PM_[^_]*$", "", dataset_id),
    dataset_mods = gsub(".*_", "", dataset_id)
  ) %>% 
  left_join(meta_ds, by = c("dataset_id_orig" = "dataset_id")) %>%
  left_join(meta_ms, by = "method_id") %>%
  # left_join(meta_metrics, by = "metric_id") %>%
  spread(metric_id, value) %>% 
  mutate(
    format_check = (correct_format + finished) / 2,
    logp1_mse = log(mse+1)
  )
write_tsv(df %>% gather(metric_id, value, -starts_with("dataset_"), -starts_with("method_"), -starts_with("metric_")), "results/pilot_predict_modality_scores.tsv")
```

```{r summtsv, include=FALSE}
replace_inf <- function(x) ifelse(is.infinite(x), max(x[is.finite(x)]), x)
summ <- df %>% 
  gather(metric_id, value, -starts_with("dataset_"), -starts_with("method_"), -starts_with("metric_")) %>% 
  mutate(value = replace_inf(value)) %>% # replace infinite values with the max
  group_by(method_id, metric_id) %>%
  summarise(
    mean = mean(value),
    sd = sd(value),
    var = var(value),
    .groups = "drop"
  ) %>% 
  left_join(meta_ms, by = "method_id")
write_tsv(summ, "results/pilot_predict_modality_summary.tsv")
```


\newpage
## Visualise results
```{r gather, echo=FALSE}
# gather columns from wide to long format
dfg <- df %>%
  mutate(filter = finished > 0) %>%
  select(-correct_format, -finished) %>%
  # filter(method_id != "dummy_solution") %>%
  gather(metric_id, value, -starts_with("dataset_"), -starts_with("method"), -filter) %>%
  filter(filter | metric_id %in% c("finished", "correct_format", "format_check"))
```

Colour by method.

```{r swarm1, echo=FALSE}
patchwork::wrap_plots(
  ggplot(dfg) +
    ggbeeswarm::geom_quasirandom(aes(method_id, value, colour = method_id), groupOnX = TRUE, size = 1) +
    facet_wrap(~metric_id, scales = "free_y") +
    scale_colour_brewer(palette = "Set1") +
    labs(x = NULL, y = "Metric Value", colour = "Method"),
  ggplot(dfg) +
    geom_boxplot(aes(method_id, value, colour = method_id)) +
    facet_wrap(~metric_id, scales = "free_y") +
    scale_colour_brewer(palette = "Set1") +
    labs(x = NULL, y = "Metric Value", colour = "Method"),
  ncol = 1
  # guides = "collect"
) &
  theme_bw() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 15, hjust = 1))
```

\newpage
Colour by dataset source.

```{r swarm2, echo=FALSE}
patchwork::wrap_plots(
  ggplot(dfg) +
    ggbeeswarm::geom_quasirandom(aes(method_id, value, colour = dataset_source), groupOnX = TRUE, size = 1) +
    facet_wrap(~metric_id, scales = "free_y") +
    scale_colour_brewer(palette = "Set2") +
    labs(x = NULL, y = "Metric Value", colour = "Dataset\nsource"),
  ggplot(dfg) +
    geom_boxplot(aes(method_id, value, colour = dataset_source)) +
    facet_wrap(~metric_id, scales = "free_y") +
    scale_colour_brewer(palette = "Set2") +
    labs(x = NULL, y = "Metric Value", colour = "Dataset\nsource"),
  ncol = 1
  # guides = "collect"
) &
  theme_bw() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 15, hjust = 1))
```

\newpage
Colour by modality group.

```{r swarm3, echo=FALSE}
patchwork::wrap_plots(
  ggplot(dfg) +
    ggbeeswarm::geom_quasirandom(aes(method_id, value, colour = dataset_mods), groupOnX = TRUE, size = 1) +
    facet_wrap(~metric_id, scales = "free_y") +
    scale_colour_brewer(palette = "Set3") +
    labs(x = NULL, y = "Metric Value", colour = "Modality\ngroup"),
  ggplot(dfg) +
    geom_boxplot(aes(method_id, value, colour = dataset_mods)) +
    facet_wrap(~metric_id, scales = "free_y") +
    scale_colour_brewer(palette = "Set3") +
    labs(x = NULL, y = "Metric Value", colour = "Modality\ngroup"),
  ncol = 1
  # guides = "collect"
) &
  theme_bw() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 15, hjust = 1))
```

\newpage
Comparing most interesting metrics.
```{r scatter1, fig.width=10, fig.height=8}
patchwork::wrap_plots(
  ggplot(df, aes(mean_pearson_per_cell, logp1_mse)) + geom_point(aes(colour = dataset_source)) + facet_wrap(~method_type),
  ggplot(df, aes(logp1_mse, mean_pearson_per_gene)) + geom_point(aes(colour = dataset_source)) + facet_wrap(~method_type),
  ggplot(df, aes(mean_pearson_per_cell, mean_pearson_per_gene)) + geom_point(aes(colour = dataset_source)) + facet_wrap(~method_type),
  ncol = 1
) & theme_bw() & scale_colour_brewer(palette = "Set2")
```
```{r scatter2, fig.width=10, fig.height=6}
patchwork::wrap_plots(
  ggplot(df, aes(mean_pearson_per_cell, logp1_mse)) + geom_point(aes(colour = method_type)) + facet_wrap(~dataset_source, nrow = 1),
  ggplot(df, aes(logp1_mse, mean_pearson_per_gene)) + geom_point(aes(colour = method_type)) + facet_wrap(~dataset_source, nrow = 1),
  ggplot(df, aes(mean_pearson_per_cell, mean_pearson_per_gene)) + geom_point(aes(colour = method_type)) + facet_wrap(~dataset_source, nrow = 1),
  ncol = 1
) & theme_bw() & scale_colour_brewer(palette = "Set2")
```

```{r bar, fig.width=10, fig.height=4}
ggplot(dfg %>% filter(metric_id %in% c("mean_pearson_per_cell", "mean_pearson_per_gene", "logp1_mse"))) + 
  geom_histogram(aes(value, fill = method_type)) + 
  facet_grid(method_type~metric_id, scales = "free_x") +
  theme_bw()
```
