functionality:
  name: dummy_meanpergene
  namespace: predict_modality_methods
  version: dev
  description: Returns the mean expression value per gene.
  info:
    type: negative_control
    label: Mean per gene
  authors:
    - name: Alex Tong
      email: alexandertongdev@gmail.com
      roles: [ author, maintainer ]
      props: { github: atong01 }
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_train_mod1"
      alternatives: ["-i1"]
      type: "file"
      example: "dataset_mod1_train.h5ad"
      description: Censored dataset, training cells.
      required: true
    - name: "--input_test_mod1"
      alternatives: ["-i1"]
      type: "file"
      example: "dataset_mod1_test.h5ad"
      description: Censored dataset, test cells.
      required: true
    - name: "--input_train_mod2"
      alternatives: ["-i2"]
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: ../../unit_tests/test_method.py
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, scipy, sklearn ]
  - type: nextflow
    publish: true
    labels: [ lowmem, lowtime, lowcpu ]
