name: viash build docker CI

on:
  push:
    branches: [ main ]

jobs:
  viash-build-docker:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: true
      matrix:
        config:
        - {name: 'common', os: ubuntu-latest }
        - {name: 'predict_modality', os: ubuntu-latest }
        - {name: 'match_modality', os: ubuntu-latest }
        - {name: 'joint_embedding', os: ubuntu-latest }

    steps:
    - uses: actions/checkout@v2

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Build components
      run: |
        # allow publishing the target folder
        sed -i '/^target\/$/d' .gitignore
        
        # only build nextflow targets
        bin/viash_build -p docker -m release -t main_build -q "${{ matrix.config.name }}"
        
    - name: Run tests
      run: |
        # create check_results folder
        sed -i '/^check_results\/$/d' .gitignore
        mkdir check_results

        # run tests
        # bin/viash_test -p docker -m release -t main_build
        # don't run tests

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push containers
      run: |
        bin/viash_push -m release -t main_build
        
    - name: Upload check results
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check_results
